---
# task file for wildfly

- name: Create wildfly etc directory
  file: path={{ wildfly_conf_dir }} owner={{ wildfly_user }}
        group={{ wildfly_group }} mode=750 state=directory

- name: Copy wildfly configuration
  template: src=wildfly.conf.j2 dest={{ wildfly_conf_dir }}/wildfly.conf
            owner=root group=root mode=0640
  notify:
    - restart wildfly
    - change standalone data mode

- name: Copy wildfly properties file
  template: src=wildfly.properties.j2 owner={{ wildfly_user }}
            group={{ wildfly_group }} mode=0640
            dest={{ wildfly_conf_dir }}/wildfly.properties
  notify:
    - restart wildfly
    - change standalone data mode

- name: Copy wildfly init script
  template: src=wildfly.init.j2 dest={{ wildfly_init_dir }}/wildfly owner=root
            group=root mode=0750
  when: ansible_service_mgr == 'init'
  notify:
    - restart wildfly
    - change standalone data mode

- name: Copy wildfly systemd unit file
  template: src=wildfly.service.j2 dest={{ wildfly_systemd_dir }}/wildfly owner=root
            group=root mode=0640
  when: ansible_service_mgr == 'systemd'
  notify:
    - restart wildfly
    - change standalone data mode

- name: Open wildfly management http tcp port
  firewalld: port={{ wildfly_manage_http_port }}/tcp permanent=true immediate=true
             state=enabled

- name: Open wildfly management http udp port
  firewalld: port={{ wildfly_manage_http_port }}/udp permanent=true immediate=true
             state=enabled

- name: Open wildfly management https tcp port
  firewalld: port={{ wildfly_manage_https_port }}/tcp permanent=true immediate=true
             state=enabled

- name: Open wildfly management https udp port
  firewalld: port={{ wildfly_manage_https_port }}/udp permanent=true immediate=true
             state=enabled

- name: Open wildfly http tcp port
  firewalld: port={{ wildfly_http_port }}/tcp permanent=true immediate=true
             state=enabled

- name: Open wildfly http udp port
  firewalld: port={{ wildfly_http_port }}/udp permanent=true immediate=true
             state=enabled

- name: Open wildfly https tcp port
  firewalld: port={{ wildfly_https_port }}/tcp permanent=true immediate=true
             state=enabled

- name: Open wildfly https udp port
  firewalld: port={{ wildfly_https_port }}/udp permanent=true immediate=true
             state=enabled

- name: Enable and start the service
  service: name=wildfly enabled=yes state=started

- name: Change standalone data mode
  file: path={{ wildfly_dir }}/standalone/data mode=0750 recurse=yes
        owner={{ wildfly_user }} group={{ wildfly_group }}

- name: Delete wildfly tar file
  file: path={{ wildfly_download_dir }}/{{ wildfly_download_file }}
        state=absent

- name: Create a version file
  template: src=version.j2 dest={{ wildfly_version_file }} mode=0750
            owner={{ wildfly_user }} group={{ wildfly_group }}
